//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Midtrans.Payment.Core.Request
{
    public partial class SubscriptionRequest
    {
		[Required]
		public int DurationOfUse{ get; set; }
		public Guid? IdGuest{ get; set; }
		[Required]
		public Guid IdSubscription{ get; set; }
		public Guid? IdUser{ get; set; }
		[Required]
		public string PaymentMethod{ get; set; }
		[Required]
		public string PaymentStatus{ get; set; }
		[Required]
		public DateTime ScheduledDate{ get; set; }
		[Required]
		public System.TimeSpan ScheduledHours{ get; set; }
		[Required]
		public DateTime TransactionDate{ get; set; }

    }
}

