//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Midtrans.Payment.Core.Request
{
    public partial class RefSubscriptionRequest
    {
		[Required]
		public string NameSubscription{ get; set; }
		[Required]
		public decimal Pricing{ get; set; }
		[Required]
		public string TypeSubscription{ get; set; }

    }
}

