//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Midtrans.Payment.Data;
using Midtrans.Payment.Data.Model;
using Midtrans.Payment.Shared.Attributes;
using Midtrans.Payment.Core.Response;
using Midtrans.Payment.Core.Helper;

namespace Midtrans.Payment.Core.Subscription.Query
{
    public class GetSubscriptionListRequest : ListRequest,IListRequest<GetSubscriptionListRequest>,IRequest<ListResponse<SubscriptionResponse>>
    {
    }
    internal class GetSubscriptionListHandler : IRequestHandler<GetSubscriptionListRequest, ListResponse<SubscriptionResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetSubscriptionListHandler(
            ILogger<GetSubscriptionListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<SubscriptionResponse>> Handle(GetSubscriptionListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<SubscriptionResponse> result = new ListResponse<SubscriptionResponse>();
            try
            {
				var query = _context.Entity<Midtrans.Payment.Data.Model.TrsSubscription>().AsQueryable();

				#region Filter
				Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, object>> column_sort = null;
				List<Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, bool>>> where = new List<Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				result.List = _mapper.Map<List<SubscriptionResponse>>(data_list);
				result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List Subscription", request);
                result.Error("Failed Get List Subscription", ex.Message);
            }
            return result;
        }

        #region List Utility
		private (Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, bool>> where, Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, object>> result_order = null;
			Expression<Func<Midtrans.Payment.Data.Model.TrsSubscription, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
								else
								result_where = (d=>d.Id == Guid.Empty);
						}
						else
							result_order = (d => d.Id);
					break;
					case "durationofuse" : 
						if(is_where){
							if (int.TryParse(search, out var _DurationOfUse))
								result_where = (d=>d.DurationOfUse == _DurationOfUse);
						}
						else
							result_order = (d => d.DurationOfUse);
					break;
					case "idguest" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdGuest))
								result_where = (d=>d.IdGuest == _IdGuest);
								else
								result_where = (d=>d.IdGuest == Guid.Empty);
						}
						else
							result_order = (d => d.IdGuest);
					break;
					case "idsubscription" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdSubscription))
								result_where = (d=>d.IdSubscription == _IdSubscription);
								else
								result_where = (d=>d.IdSubscription == Guid.Empty);
						}
						else
							result_order = (d => d.IdSubscription);
					break;
					case "iduser" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdUser))
								result_where = (d=>d.IdUser == _IdUser);
								else
								result_where = (d=>d.IdUser == Guid.Empty);
						}
						else
							result_order = (d => d.IdUser);
					break;
					case "paymentmethod" : 
						if(is_where){
							result_where = (d=>d.PaymentMethod.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.PaymentMethod);
					break;
					case "paymentstatus" : 
						if(is_where){
							result_where = (d=>d.PaymentStatus.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.PaymentStatus);
					break;
					case "scheduleddate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _ScheduledDate))
								result_where = (d=>d.ScheduledDate == _ScheduledDate);
						}
						else
							result_order = (d => d.ScheduledDate);
					break;
					case "scheduledhours" : 
						if(is_where){
							if (System.TimeSpan.TryParse(search, out var _ScheduledHours))
								result_where = (d=>d.ScheduledHours == _ScheduledHours);
						}
						else
							result_order = (d => d.ScheduledHours);
					break;
					case "transactiondate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _TransactionDate))
								result_where = (d=>d.TransactionDate == _TransactionDate);
						}
						else
							result_order = (d => d.TransactionDate);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

