//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using Microsoft.Extensions.Logging;
using Midtrans.Payment.Data;
using Midtrans.Payment.Data.Model;
using Midtrans.Payment.Shared.Attributes;
using Midtrans.Payment.Core.Response;

namespace Midtrans.Payment.Core.Subscription.Query
{

    public class GetRefSubscriptionByIdRequest : IRequest<ObjectResponse<RefSubscriptionResponse>>
    {
        [Required]
        public Guid Id { get; set; }
    }
    internal class GetRefSubscriptionByIdHandler : IRequestHandler<GetRefSubscriptionByIdRequest, ObjectResponse<RefSubscriptionResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetRefSubscriptionByIdHandler(
            ILogger<GetRefSubscriptionByIdHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }
        public async Task<ObjectResponse<RefSubscriptionResponse>> Handle(GetRefSubscriptionByIdRequest request, CancellationToken cancellationToken)
        {
            ObjectResponse<RefSubscriptionResponse> result = new ObjectResponse<RefSubscriptionResponse>();
            try
            {
                var item = await _context.Entity<Midtrans.Payment.Data.Model.RefSubscription>().Where(d => d.Id == request.Id).FirstOrDefaultAsync();
                if (item != null)
                {
                    result.Data = _mapper.Map<RefSubscriptionResponse>(item);
                    result.OK();
                }
                else
                    result.NotFound($"Id Midtrans.Payment.Data.Model.RefSubscription {request.Id} Tidak Ditemukan");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get Detail Subscription", request.Id);
                result.Error("Failed Get Detail Subscription", ex.Message);
            }
            return result;
        }
    }
}

