//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutoMapper;
using MediatR;
using Vleko.DAL.Interface;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;
using Microsoft.Extensions.Logging;
using Midtrans.Payment.Data;
using Midtrans.Payment.Data.Model;
using Midtrans.Payment.Shared.Attributes;
using Midtrans.Payment.Core.Response;
using Midtrans.Payment.Core.Helper;

namespace Midtrans.Payment.Core.SubscriptionPack.Query
{
    public class GetSubscriptionPackListRequest : ListRequest,IListRequest<GetSubscriptionPackListRequest>,IRequest<ListResponse<SubscriptionPackResponse>>
    {
    }
    internal class GetSubscriptionPackListHandler : IRequestHandler<GetSubscriptionPackListRequest, ListResponse<SubscriptionPackResponse>>
    {
        private readonly ILogger _logger;
        private readonly IMapper _mapper;
        private readonly IUnitOfWork<ApplicationDBContext> _context;
        public GetSubscriptionPackListHandler(
            ILogger<GetSubscriptionPackListHandler> logger,
            IMapper mapper,
            IUnitOfWork<ApplicationDBContext> context
            )
        {
            _logger = logger;
            _mapper = mapper;
            _context = context;
        }

        public async Task<ListResponse<SubscriptionPackResponse>> Handle(GetSubscriptionPackListRequest request, CancellationToken cancellationToken)
        {
            ListResponse<SubscriptionPackResponse> result = new ListResponse<SubscriptionPackResponse>();
            try
            {
				var query = _context.Entity<Midtrans.Payment.Data.Model.RefSubscriptionPack>().AsQueryable();

				#region Filter
				Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, object>> column_sort = null;
				List<Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, bool>>> where = new List<Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, bool>>>();
				if (request.Filter != null && request.Filter.Count > 0)
				{
					foreach (var f in request.Filter)
					{
						var obj = ListExpression(f.Search, f.Field, true);
						if (obj.where != null)
							where.Add(obj.where);
					}
				}
				if (where != null && where.Count() > 0)
				{
					foreach (var w in where)
					{
						query = query.Where(w);
					}
				}
				if (request.Sort != null)
                {
					column_sort = ListExpression(request.Sort.Field, request.Sort.Field, false).order!;
					if(column_sort != null)
						query = request.Sort.Type == SortTypeEnum.ASC ? query.OrderBy(column_sort) : query.OrderByDescending(column_sort);
					else
						query = query.OrderBy(d=>d.Id);
				}
				#endregion

				var query_count = query;
				if (request.Start.HasValue && request.Length.HasValue && request.Length > 0)
					query = query.Skip((request.Start.Value - 1) * request.Length.Value).Take(request.Length.Value);
				var data_list = await query.ToListAsync();

				result.List = _mapper.Map<List<SubscriptionPackResponse>>(data_list);
				result.Filtered = data_list.Count();
				result.Count = await query_count.CountAsync();
				result.OK();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed Get List SubscriptionPack", request);
                result.Error("Failed Get List SubscriptionPack", ex.Message);
            }
            return result;
        }

        #region List Utility
		private (Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, bool>> where, Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, object>> order) ListExpression(string search, string field, bool is_where)
		{
			Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, object>> result_order = null;
			Expression<Func<Midtrans.Payment.Data.Model.RefSubscriptionPack, bool>> result_where = null;
            if (!string.IsNullOrWhiteSpace(search) && !string.IsNullOrWhiteSpace(field))
            {
                field = field.Trim().ToLower();
                search = search.Trim().ToLower();
                switch (field)
                {
					case "createby" : 
						if(is_where){
							result_where = (d=>d.CreateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.CreateBy);
					break;
					case "createdate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _CreateDate))
								result_where = (d=>d.CreateDate == _CreateDate);
						}
						else
							result_order = (d => d.CreateDate);
					break;
					case "durationhour" : 
						if(is_where){
							if (int.TryParse(search, out var _DurationHour))
								result_where = (d=>d.DurationHour == _DurationHour);
						}
						else
							result_order = (d => d.DurationHour);
					break;
					case "id" : 
						if(is_where){
							if (Guid.TryParse(search, out var _Id))
								result_where = (d=>d.Id == _Id);
								else
								result_where = (d=>d.Id == Guid.Empty);
						}
						else
							result_order = (d => d.Id);
					break;
					case "idsubscription" : 
						if(is_where){
							if (Guid.TryParse(search, out var _IdSubscription))
								result_where = (d=>d.IdSubscription == _IdSubscription);
								else
								result_where = (d=>d.IdSubscription == Guid.Empty);
						}
						else
							result_order = (d => d.IdSubscription);
					break;
					case "isadditionalservice" : 
						if(is_where){
							if (bool.TryParse(search, out var _IsAdditionalService))
								result_where = (d=>d.IsAdditionalService == _IsAdditionalService);
						}
						else
							result_order = (d => d.IsAdditionalService);
					break;
					case "subscriptionpackname" : 
						if(is_where){
							result_where = (d=>d.SubscriptionPackName.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.SubscriptionPackName);
					break;
					case "updateby" : 
						if(is_where){
							result_where = (d=>d.UpdateBy.Trim().ToLower().Contains(search));
						}
						else
							result_order = (d => d.UpdateBy);
					break;
					case "updatedate" : 
						if(is_where){
							if (DateTime.TryParse(search, out var _UpdateDate))
								result_where = (d=>d.UpdateDate == _UpdateDate);
						}
						else
							result_order = (d => d.UpdateDate);
					break;

                }
            }
            return (result_where, result_order);
        }
        #endregion
    }
}

